version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./net/nginx.conf:/etc/nginx/nginx.conf
  shiny:
    image: tronos-shiny:latest
    container_name: shiny
    restart: unless-stopped
    expose:
      - 3838
    volumes:
      - ./app/:/srv/shiny-server/tronos
      - ./net/shiny-server.conf:/etc/shiny/shiny-server.conf
